Unable to find image 'sae_monitoramento_back:latest' locally
docker: Error response from daemon: pull access denied for sae_monitoramento_back, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
